#!/usr/bin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority filter; policy drop;
        iif "lo" accept
        ct state invalid drop
        ct state established,related accept
        iifname "tailscale0" accept
        udp dport 41641 accept
        iifname "08834wg" accept comment "wg-in"
        udp sport 51820 accept comment "wg-udp-in"
    }

    chain output {
        type filter hook output priority filter; policy drop;
        oif "lo" accept
        ct state invalid drop
        ct state established,related accept
        oifname "tailscale0" accept
        udp dport 41641 accept
        oifname "08834wg" accept comment "wg-out"
        udp dport 51820 accept comment "wg-udp-out"
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
    }
}
