#PATH: /etc/systemd/resolved.conf.d/alx_dns_servers.conf
#ALSO check: /etc/systemd/resolved.conf
[Resolve]
# DNS con SNI para DoT
DNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com
# Fallback (opcional)
FallbackDNS=8.8.8.8 9.9.9.9
DNSOverTLS=no
Cache=yes
