[Interface]
# Key for wireguard
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = OEVxR37YriSSo8ArHpFkpVBs3kdwTqo42RdWERbLInc=
Address = 10.2.0.2/32
DNS = 10.2.0.1
# Killswitch, prevent all interfaces except wg
PostUp  = iptables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -I OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
PreDown = iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT && ip6tables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT

[Peer]
# CA-FREE#12
PublicKey = WajeJDezN7JFBe//v/VMsASFyBUk01Hlyvjb0T+dTjE=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 79.127.254.92:51820

PersistentKeepalive = 25
